### ISSUE TITLE
Join up in Team 1 and work with me on Project 2.

### ISSUE THREAD

**Issue by karlnicholas** [CS111B-META-SUMMER-2016/Team1-Project2#1]
There is no particular need to join Team1 other than perhaps we can message each other more conveniently than opening issues or trying to go through email/insight.

**Comment by karlnicholas** [comment]
There is no particular need to join Team1 other than perhaps we can message each other more conveniently than opening issues or trying to go through email/insight.

**Comment by mdasc2** [comment]
If we were working together I feel like skype or something equivalent would be better than these forum postings.

**Comment by vinicius5581** [comment]
**About communication:**

I would like to propose google hangout for communication. We can use our student emails, share screens, videos and everything. 

I'll create an issue to collect the emails and I'll create a group on hangout. If you want to join please add your email on the issue.

**About tasks**

Maybe we could breakdown the work and decide who will work on what. I'll create some issues to get this train going.

**Comment by karlnicholas** [comment]
I second Google hangout. It has worked well for me in the past.

Sent from my iPhone

On Jun 28, 2016, at 1:14 AM, Vinicius Santana <notifications@github.com> wrote:

About communication:

I would like to propose google hangout for communication. We can use our student emails, share screens, videos and everything.

I'll create an issue to collect the emails and I'll create a group on hangout. If you want to join please add your email on the issue.

About tasks

Maybe we could breakdown the work and decide who will work on what. I'll create some issues to get this train going.

**Comment by karlnicholas** [comment]
Good job on the issues. I assigned myself the Student class and @vinicius5581 the Course class since that has been done. Feel free to assign yourself a task and jump in, but be aware, only 4 student to a "group project". I've sent one other invite to Andrew Furth, so hopefully he'll be along in a bit. I told him @rlim1812 has dibs on the 4th position in this project if he wants it, and we can see how its going after the midterms.
