### ISSUE TITLE
Use Student.equals test in Course.dropStudent(Student s) method.

### ISSUE THREAD

**Issue by karlnicholas** [CS111B-META-SUMMER-2016/Team1-Project2#10]
Once the Student class can test for its own identity, then use that test in the Course.dropStudent(Student s) method.

**Comment by mdasc2** [comment]
You can use a .equals for a Student class? Thought it was only Strings... I'll try it

**Comment by karlnicholas** [comment]
Yes, I should have been more clear. This was related to other issue of making a .equals in the Student class.

**Comment by karlnicholas** [comment]
Actually, to be more clear, the issue is, in the Course.dropStudents(Student s) method, instead of testing the name and the id of the sudent in the roster againt the name and the id of student passed as s, do

    if (roster[I].equals(s) ) ...

This will invoke the .equals method of the student class, which in turn tests the name and the id for you. This is cleaner object oriented programming.
