### ISSUE TITLE
course.setMaxStudents not functional

### ISSUE THREAD

**Issue by karlnicholas** [CS111B-META-SUMMER-2016/Team1-Project2#14]
See TestProject class. The below code fails.

    Course course = new Course("CS111B", 1);
    course.setMaxStudents(2);        
    // fails because max students not really set to 2
    course.addStudent(studentA);
    course.addStudent(studentB);

**Comment by mdasc2** [comment]
It doesn't fail because max students isn't set to 2. It is set to 2 as you can see from the printRoster()

Its because with the code we have now the original array that is constructed in the constructor isn't replaced with a resized one from setMaxStudents. It keeps the old one. I fixed that.
