### ISSUE TITLE
dropStudent(int position) Keep or Delete?

### ISSUE THREAD

**Issue by mdasc2** [CS111B-META-SUMMER-2016/Team1-Project2#17]
I deleted it in the recent commit I did, but you made some changes in the commit before this one, so I'm wondering if you wanted to keep it or not.

**Comment by karlnicholas** [comment]
Well, here is the comment in the notes:

>Note: There are different approaches to implementing this method. Any approach is fine, but be sure to test your method thoroughly considering lots of different possible cases. (Use your driver program for this!)

If we are using the driver program to test for "different implementations" then ProjectDriver will only be able to see different signatures, not different styles of code inside the methods. I feel like he is hinting that there it could be done with an `int position` or a `Student s` and so I think we should keep it and we should expand the driver program to test both implementations. 

From an interface or API point of view, it could be very convenient to be able to remove students simply based on their position in the list without having to create student objects just for the purpose of removing them from the roster. We also covered method overloads a couple chapters ago and this is exactly that. So, yea, I'd like to see both methods and also to expand the ProjectDriver to use them both.

We also have to expand project driver to use the CourseAL class, so my guess is it's going to be OK to add all this into ProjectDriver for the assignment.

**Comment by mdasc2** [comment]
I still think when he says implementing this method, its how you write how to drop the Students. Not hinting at trying to do it with different arguments. 

For an interface/API I agree removing by position sounds good, but it seems like extra fluff that isn't needed. But I guess a self imposed assignment is as good as any to practice with.

Also do you know where Vinicius has been? It seems like only me and you have worked on the assignment for the past few days.

**Comment by karlnicholas** [comment]
Don’t know where Vini has been, though he did promise (on hangouts I think) do get caught on this weekend. We have until Tuesday night, and the Course class seems to be in good enough shape that he can use it to model the add, drop and print students class in the CourseAL class. I think he was interested in doing that because he created the class. I added up to the get/set maxStudents. Perhaps you can make an issue for it or update the extra-credit issue #8 and assign him to it. I think that's fair.

**Comment by karlnicholas** [comment]
Re-read the project specs. It's pretty clear about dropStudent. Sorry for the confusion.
