### ISSUE TITLE
Why are we using Variable Length Parameter Lists on our classes definitions?

### ISSUE THREAD

**Issue by vinicius5581** [CS111B-META-SUMMER-2016/Team1-Project2#18]
I started reviewing the current code and one thing that caught my attention is the fact that we are using a Variable Length Parameter List on our ProjectDriver class main method signature.

`public static void main(String... args) ` 

I wonder why we are doing that over the traditional array.

`public static void main(String[] args) `

This is just me been curious and I would like to understand if there is benefits on one method over the other.

**Comment by karlnicholas** [comment]
Exactly the same. The … notation was introduced in 1.5 (I think as the varargs feature - Java int… array notation <http://stackoverflow.com/questions/580743/java-int-array-notation?answertab=votes#tab-top> ) I just think it looks cooler.  Plus, it was discussed in this chapter’s slides.

**Comment by vinicius5581** [comment]
Fair enough. Closing this issue.
