### ISSUE TITLE
Package project and submit Java and class files to insight.

### ISSUE THREAD

**Issue by karlnicholas** [CS111B-META-SUMMER-2016/Team1-Project2#19]
Who's going to do the submission?

**Comment by mdasc2** [comment]
I'll do it, it you guys don't mind. I'll turn it in tomorrow after you guys check the rest.

**Comment by karlnicholas** [comment]
Works for me. I'll be looking at it tomorrow afternoon so open an issue if anything you want me to look at.

**Comment by mdasc2** [comment]
Well, I'm trying to figure out why what Vinicius had didn't work, and it seems like it has something to do with the maxStudent variable.

He set the constructor with setMaxStudents and logically it seems to make sense to me, but a nullpointer happens when you construct with 		

setCourseName(courseName);
setMaxStudents(maxStudents);

But if the constructor passes maxStudents through into setMaxStudents then there shouldn't be a problem. As its not interacting with the unset this.MaxStudents, or is it? I'm not sure...

**Comment by karlnicholas** [comment]
I moved the general testing of Course class into the Driver Project as per project specs. If anyone doesn't like it or disagrees, feel free to change/remove as you see fit.

I sign off on this project. Feel free to make any other little changes as you see fit, but it all looks good to me and I'm very pleased with the effort everyone put into this. I think we'll do well with the grade.

**Comment by mdasc2** [comment]
http://imgur.com/a/G2vpm

Here is some proof I turned it in.

**Comment by karlnicholas** [comment]
Dude, you have to put in the .class files a well.

**Comment by karlnicholas** [comment]
Andrew, 

 

Look at Project 1 questions, question named “Submission”. It says to submit both the .java and the .class files. I’m pretty sure that’s what Prof. Giambattista wants. Can you please redo the submission? Didn’t you do that for Project1 as well?

 

Karl.

**Comment by vinicius5581** [comment]
I though we were doing the submission at 10pm and last review until 4pm Today.

 Should I understand that the submission is done already?

**Comment by karlnicholas** [comment]
I was good at 12:00 pm today.

I think we need to submit both the .class files and the .java files.

**Comment by karlnicholas** [comment]
I have to sign off now, though I will check my email through my phone later.

 

Karl.

**Comment by vinicius5581** [comment]
@anfruth  Did you submit it yet?

**Comment by vinicius5581** [comment]
If I dont hear back I will be submitting the project at 10pm tonight.

**Comment by mdasc2** [comment]
Are these the class files of which you speak of? And if so I have added them to the zip file and reuploaded them.

And for project 1 I just turned in the java files and was alright. But here.

http://imgur.com/a/owD01

@vinicius5581 Not sure who you are referring to. But if you read above I did turn it in.

**Comment by karlnicholas** [comment]
Hi Andrew,

Yea, looks good. Thanks for redoing it. I was under strong impression from somewhere both class and Java files were to be submitted.

**Comment by mdasc2** [comment]
I guess to be safe turn in both since he said so, but it's not really stated anywhere besides that forum post.

**Comment by karlnicholas** [comment]
Yea, I agree. I'll put another question on the forum to clarify things.

**Comment by mdasc2** [comment]
Alright, make sure to inform us when you get the answer

**Comment by karlnicholas** [comment]
Checked. They want the "class" files, not the ".class" files. So, no need to send in the compiled files.
