### ISSUE TITLE
Google Hangout - Please provide your ccsf email

### ISSUE THREAD

**Issue by vinicius5581** [CS111B-META-SUMMER-2016/Team1-Project2#2]
Please add you ccsf email on a comment to join our Google hangout group.

**Comment by vinicius5581** [comment]
Name: Osmar "Vinicius" Santana
Email: osantana@mail.ccsf.edu

**Comment by karlnicholas** [comment]
Knichola@mail.ccsf.edu

Sent from my iPhone

On Jun 28, 2016, at 1:16 AM, Vinicius Santana <notifications@github.com> wrote:

Name: Osmar "Vinicius" Santana
Email: osantana@mail.ccsf.edu

**Comment by mdasc2** [comment]
achow28@mail.ccsf.edu

**Comment by karlnicholas** [comment]
achow28@mail.ccsf.edu has not yet accepted my invitation to hangouts.google.com. Not that we've been using it, but it might be good to meet on hangsout at least once for project sign-off.

**Comment by mdasc2** [comment]
Accepted, thought I would get an email about the invitation, but had to go onto hangouts.google.com to see it

**Comment by karlnicholas** [comment]
I'm surprised you didn't. Issue closed.
