### ISSUE TITLE
Grades reported?

### ISSUE THREAD

**Issue by karlnicholas** [CS111B-META-SUMMER-2016/Team1-Project2#21]
Did we get grades for this project yet? I don't see anything on insight.

**Comment by mdasc2** [comment]
No, I don't see one either. Also are we doing a group for project 4?

**Comment by karlnicholas** [comment]
Prof. Loui is probably going slow on them. I put a Q in insight. I actually handed in Project 4 already but happy to consult or answer questions if you want.

**Comment by karlnicholas** [comment]
Looks like we got a 98% on the main effort and 20 points on the extra-credit. Thanks for the extra effort guys and job well done.

**Comment by mdasc2** [comment]
Well I don't know if your watching this anymore, but how did you manage to incorporate lines into this? 

When i use an array to hold the points of the line when you click the pen off and move your mouse somewhere else and click the pen on. The drawline method connects the last point I was on to the point I moved my cursor to which shouldn't happen. How did you deal with it?

**Comment by karlnicholas** [comment]
I'm not sure I understand the question. If you want to look at my GitHub repo you can see what I handed in at https://github.com/karlnicholas/Project4.
