### ISSUE TITLE
Part 1- The Student Class (10 points)

### ISSUE THREAD

**Issue by vinicius5581** [CS111B-META-SUMMER-2016/Team1-Project2#3]
Write a class called Student. A student is described by:

- a name
- an ID (text-based, such as "A146")
- whether or not tuition is paid

Write a constructor, getters and setters, and a toString method for this class.

**Comment by karlnicholas** [comment]
@vinicius5581 changes look good. I didn't add a default constructor, but can do if we think we need it. Closing issue.
