### ISSUE TITLE
Part 4- Course Methods (50 points)

### ISSUE THREAD

**Issue by vinicius5581** [CS111B-META-SUMMER-2016/Team1-Project2#6]
Write the following 3 methods in the Course class:

public boolean addStudent(Student s)

if there is room for the student, add the student to the roster and return true

return false otherwise

public boolean dropStudent(Student s)

if the student is currently in the roster, remove them from the roster and return true

return false otherwise

Note: There are different approaches to implementing this method. Any approach is fine, but be sure to test your method thoroughly considering lots of different possible cases. (Use your driver program for this!)

public void printRoster()

print how many students are enrolled in the course; print an appropriate message if there are no students yet enrolled

print the list of each student on a single line (use good object-oriented principles to access a text representation of each student!)

**Comment by karlnicholas** [comment]
> Note: There are different approaches to implementing this (dropStudent) method. Any approach is fine, but be sure to test your method thoroughly considering lots of different possible cases. (Use your driver program for this!)

We have two approaches for the dropStudent method, so I think that is good. Closing this issue as essentially implemented.
