### ISSUE TITLE
Part 5- Driver Program (20 points)

### ISSUE THREAD

**Issue by vinicius5581** [CS111B-META-SUMMER-2016/Team1-Project2#7]
Write a driver program that does the following (in this order). Note that your driver program is not interactive with the user.

creates six students

creates a course that can hold five students

prints the course

prints the roster

adds the first five students to the course

tries to add the sixth student and prints a message if any add fails

prints the roster

drops the third student from the course

prints the roster

tries again to add the sixth student to the course

prints the roster

**Comment by karlnicholas** [comment]
First shot at driver program seems to be able to access all methods except `dropStudent(student3)`.

**Comment by vinicius5581** [comment]
Looks like this method haven't being implemented yet as per: 

https://github.com/CS111B-META-SUMMER-2016/Team1-Project2/commit/6dd77067dc682a4bf1a2744f39e81672df12d7b7

**Comment by karlnicholas** [comment]
I am thinking that the method signature should be `void dropStudent(int rosterPosition)` as it seems to read that way. Perhaps a insight question?

**Comment by karlnicholas** [comment]
@mdasc2 since you added the roster into the course class are you going to implement the dropStudent method?

**Comment by karlnicholas** [comment]
ProjectDriver class looks good at this point.
