### ISSUE TITLE
Extra Credit (20 points)

### ISSUE THREAD

**Issue by vinicius5581** [CS111B-META-SUMMER-2016/Team1-Project2#8]
Extra Credit (20 points)

Write a class called CourseAL. This class has the same methods as Course. But, instead of using a Student[] to store the roster, use an ArrayList. Re-write the Course methods to work with the ArrayList. Take advantage of the methods provided in the ArrayList class!

If you complete the extra credit, submit Course and CourseAL.

**Comment by karlnicholas** [comment]
Added properties and setMaxStudents() method. Needs add, drop and print.

**Comment by vinicius5581** [comment]
Having problems with add student. I'll keep working on it Tomorrow, but please point out if you see why addStudent is failing.

**Comment by karlnicholas** [comment]
b/c you removed the studentRoster allocation from setMaxStudents().

**Comment by mdasc2** [comment]
That shouldn't matter because the array allocates extra room for itself so you should just be able to add it straight up

**Comment by vinicius5581** [comment]
I've add the student names to the msgs displayed when a student is added or when the roster has no more space.

**Comment by karlnicholas** [comment]
I had put logic to reallocate studentRoster when setMaxStudents was changed but I see that was logically incorrect because ArrayList changes size dynamically as was pointed out. The CourseAL code looks very good to me. Closing issue.
